from tkinter.font import *

class GraphicsContext:
    strokeColor: str
    fillColor: str
    font: Font
    originX: int
    originY: int
    def __init__(self, canvas) -> None: ...
    def setStrokeColor(self, color) -> None: ...
    def setFillColor(self, color) -> None: ...
    def setFont(self, font) -> None: ...
    def setOrigin(self, x, y) -> None: ...
    def drawLine(self, x1, y1, x2, y2, dashLength: int = 0, dashGap: int = 0) -> None: ...
    def fillRect(self, x1, y1, x2, y2) -> None: ...
    def strokeRect(self, x1, y1, x2, y2) -> None: ...
    def drawString(self, string, x, y, centered: bool = False) -> None: ...

class GraphicsEventSystem:
    width: Any
    height: Any
    graphicsContext: GraphicsContext
    def __init__(self, width, height) -> None: ...
    def start(self) -> None: ...
    def handlePaint(self) -> None: ...
    def requestRepaint(self) -> None: ...
    def handleMousePressed(self, x, y) -> None: ...
    def handleMouseReleased(self, x, y) -> None: ...
    def handleMouseMoved(self, x, y) -> None: ...
    def handleMouseDragged(self, x, y) -> None: ...
    def handleKeyPressed(self, char) -> None: ...

COLOR_BLACK: str
COLOR_GRAY: str
COLOR_LIGHT_GRAY: str
COLOR_WHITE: str
COLOR_RED: str
COLOR_DARK_GREEN: str
COLOR_GREEN: str
COLOR_LIGHT_GREEN: str
COLOR_DARK_BLUE: str
COLOR_BLUE: str
COLOR_LIGHT_BLUE: str
COLOR_TURQUOISE: str
COLOR_YELLOW: str
COLOR_ORANGE: str
COLOR_BROWN: str
COLOR_PURPLE: str
COLOR_PINK: str
COLOR_CLEAR: str
